In [1]:
import numpy as np

# Define two matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# Perform matrix multiplication
result = np.dot(A, B)

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("\nProduct of A dot B:")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Product of A dot B:
[[ 58  64]
 [139 154]]
